window.QUIZ_DATA = {
 "generatedAt": "2026-08-26T13:06:16",
 "sources": [
  {
   "file": "output/260714/공통영어1_모의25.md",
   "title": "공통영어1 모의 문제 — 25문항 (상산고 유형 기반 생성)",
   "subject": "english",
   "count": 25,
   "scopeConfirmed": false,
   "setId": "260714"
  },
  {
   "file": "output/260822/_part1_평면좌표.md",
   "title": "정답 · 해설 · 유형 (1~6번)",
   "subject": "unknown",
   "count": 0,
   "scopeConfirmed": false,
   "setId": "260822"
  },
  {
   "file": "output/260822/_part2_직선.md",
   "title": "정답 · 해설 · 유형 (7~16번)",
   "subject": "unknown",
   "count": 0,
   "scopeConfirmed": false,
   "setId": "260822"
  },
  {
   "file": "output/260822/_part3_원.md",
   "title": "정답 · 해설 · 유형",
   "subject": "unknown",
   "count": 0,
   "scopeConfirmed": false,
   "setId": "260822"
  },
  {
   "file": "output/260822/_part4_이동.md",
   "title": "",
   "subject": "unknown",
   "count": 0,
   "scopeConfirmed": false,
   "setId": "260822"
  },
  {
   "file": "output/260822/공통수학2_도형의방정식_모의40.md",
   "title": "공통수학2 「도형의 방정식」 예상 문제 40제 (2026 상산고 1학년 2학기)",
   "subject": "math2",
   "count": 40,
   "scopeConfirmed": false,
   "setId": "SET-260822-math2-40"
  }
 ],
 "problems": [
  {
   "id": "260714#1",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 1,
   "qtype": "choice",
   "stem": "다음 글의 **주제**로 가장 적절한 것은?",
   "passage": "For most of human history, doing one thing at a time was not a virtue but a necessity. The modern workplace, however, treats attention as if it were infinitely divisible—an assumption that neuroscience has steadily undermined. When we believe we are multitasking, what the brain is actually doing is switching rapidly between separate tasks, and each switch carries a hidden toll. Researchers who study this cost describe it as \"attention residue,\" a fragment of the previous task that lingers and clouds the next one. Studies suggest that people who juggle several streams of information perform worse on tests of memory and concentration than those who focus on a single task, even when they feel more productive. In a culture that prizes constant busyness, the rarest and most valuable skill may be the willingness to do less, more deeply.",
   "options": [
    "① the neurological benefits of handling several tasks at once",
    "② the hidden cost of multitasking and the value of focused attention",
    "③ why modern workplaces are more productive than in the past",
    "④ historical changes in how people organize their working day",
    "⑤ methods for measuring memory and concentration in the laboratory"
   ],
   "answer": "②",
   "typeId": "T-01",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "멀티태스킹의 숨은 비용 + 집중의 가치. ①은 정반대(E1), ③④⑤는 지엽·언급 안 됨"
  },
  {
   "id": "260714#2",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 2,
   "qtype": "choice",
   "stem": "다음 글의 **제목**으로 가장 적절한 것은?",
   "passage": "On a summer evening, a city can be several degrees warmer than the countryside around it, a phenomenon known as the urban heat island. The cause is largely material: concrete and asphalt absorb heat all day and release it slowly at night, while glass and steel trap warmth between buildings. Cars, air conditioners, and crowds add still more. The effect is not trivial; it raises energy use, worsens air quality, and endangers the elderly during heat waves. Fortunately, the remedies are well understood. Planting trees, painting roofs white, and creating parks can all cool a city measurably, turning a problem of design into an opportunity for it.",
   "options": [
    "① Why Cities Grow Faster Than Rural Areas",
    "② The Urban Heat Island and How to Cool It",
    "③ The Hidden Dangers of Air Conditioning",
    "④ How Trees Clean the Air We Breathe",
    "⑤ The Long History of Concrete and Steel"
   ],
   "answer": "②",
   "typeId": "T-01",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "열섬 현상 + 해결책. ③④⑤ 지엽, ① 무관"
  },
  {
   "id": "260714#3",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 3,
   "qtype": "choice",
   "stem": "밑줄 친 **\"you cannot pour expertise into a mind the way you pour water into a glass\"** 가 다음 글에서 의미하는 바로 가장 적절한 것은?",
   "passage": "A beginner and an expert can look at the same chessboard and see entirely different things. Where the novice sees thirty-two separate pieces, the master perceives familiar patterns, threats, and opportunities grouped into meaningful wholes. Years of practice have reshaped not just what the expert knows but how she sees. This is why simply handing someone information rarely creates skill. As one researcher put it, \"you cannot pour expertise into a mind the way you pour water into a glass.\" Real mastery is built slowly, through thousands of encounters that gradually train perception itself.",
   "options": [
    "① Experts are often unwilling to share what they know.",
    "② Expertise cannot be transferred instantly as mere information.",
    "③ The human mind has a strictly limited storage capacity.",
    "④ Drinking enough water improves concentration and learning.",
    "⑤ Beginners and experts think in exactly the same way."
   ],
   "answer": "②",
   "typeId": "T-03",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "\"물 붓듯 전문성을 부을 수 없다\"=정보 전달만으론 즉시 숙련 안 됨. ④ 표면 직역 함정(E3)"
  },
  {
   "id": "260714#4",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 4,
   "qtype": "choice",
   "stem": "밑줄 친 **\"the meaning a patient attaches to a pill can be as powerful as the chemistry inside it\"** 가 다음 글에서 의미하는 바로 가장 적절한 것은?",
   "passage": "A sugar pill should do nothing, and yet, again and again, patients who take one report real relief. This is the placebo effect, and it is far stranger than mere imagination. Brain scans show that a convincing placebo can trigger the release of the body's own painkillers, producing measurable changes. In other words, the belief that one is being treated can itself become a form of treatment. Doctors have long known that \"the meaning a patient attaches to a pill can be as powerful as the chemistry inside it.\" Understanding this has forced medicine to take seriously something it once dismissed.",
   "options": [
    "① Expensive medicines always work better than cheap ones.",
    "② A patient's beliefs can influence healing as much as the drug itself.",
    "③ Doctors should stop prescribing chemically active medication.",
    "④ Sugar pills secretly contain hidden active chemicals.",
    "⑤ Physical pain is entirely imaginary and never real."
   ],
   "answer": "②",
   "typeId": "T-03",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "믿음(의미)이 약만큼 치유에 영향. ①④⑤ 과장·왜곡"
  },
  {
   "id": "260714#5",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 5,
   "qtype": "choice",
   "stem": "다음 글의 내용과 **일치하지 않는** 것은?",
   "passage": "When a honeybee discovers a rich source of food, it returns to the hive and performs a remarkable \"waggle dance\" to tell the others where to go. By moving in a figure-eight pattern and waggling its body, the bee encodes two crucial pieces of information: the direction of the food relative to the sun, and its distance from the hive. The longer the waggle, the farther away the food lies. Other bees follow closely, reading the message through touch and vibration in the dark hive. This dance is one of the few known examples of a non-human animal communicating abstract information about a distant place.",
   "options": [
    "① The waggle dance conveys both direction and distance.",
    "② A longer waggle indicates food that is farther away.",
    "③ Bees interpret the dance through touch and vibration.",
    "④ The dance communicates the location of a distant food source.",
    "⑤ The direction is encoded relative to the hive entrance."
   ],
   "answer": "⑤",
   "typeId": "T-02",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "방향은 **태양** 기준이지 벌집 입구 기준 아님(E6 좌우·기준 뒤집기)"
  },
  {
   "id": "260714#6",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 6,
   "qtype": "essay",
   "stem": "다음 글의 밑줄 친 부분 중, **어법상 틀린** 것은?",
   "passage": "Scientists once believed that a memory, once stored, remained ①**fixed** forever. Recent research, however, has revealed a process ②**calling** reconsolidation, in which the simple act of recalling a memory makes it temporarily unstable. During this brief window, the memory can be altered before it ③**is stored** again. This helps explain why two people who ④**witnessed** the same event often remember it differently. Each time they retell the story, they may unknowingly reshape it, ⑤**adding** details that were never there.\n---",
   "options": [],
   "answer": "②",
   "typeId": "T-04",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "a process **calling→called**(과거분사 수동). 나머지 어법 정상"
  },
  {
   "id": "260714#7",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 7,
   "qtype": "essay",
   "stem": "다음 글의 밑줄 친 부분 중, 문맥상 낱말의 쓰임이 **적절하지 않은** 것은?",
   "passage": "When a species arrives in a new environment where it has no natural predators, its population can explode. Freed from the checks that once ①**limited** its growth, it spreads rapidly, often ②**outcompeting** native species for food and space. Such invaders can ③**disrupt** entire ecosystems within a few years. Efforts to remove them are usually expensive and, once the species is well established, rarely ④**successful**. For this reason, scientists stress that ⑤**encouraging** the arrival of foreign species is far cheaper than reversing the damage they cause.\n---",
   "options": [],
   "answer": "⑤",
   "typeId": "T-05",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "encouraging→**preventing**(유입 '방지'가 복구보다 싸다). E1 정반대"
  },
  {
   "id": "260714#8",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 8,
   "qtype": "essay",
   "stem": "다음 글의 밑줄 친 부분 중, 문맥상 낱말의 쓰임이 **적절하지 않은** 것은?",
   "passage": "Boredom has a bad reputation, but psychologists now see it as a useful signal rather than a ①**flaw**. When an activity fails to engage us, boredom ②**pushes** us to seek something more meaningful. In this sense, it acts like hunger, telling us that our current situation is no longer ③**rewarding**. Studies even suggest that mild boredom can ④**reduce** creativity, because a restless mind begins to wander and generate new ideas. The danger appears only when we escape boredom through ⑤**constant** distraction, never giving our thoughts the space to develop.\n---",
   "options": [],
   "answer": "④",
   "typeId": "T-05",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "reduce→**boost**(뒤 \"새 아이디어 생성\"이 근거). E1 정반대"
  },
  {
   "id": "260714#9",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 9,
   "qtype": "choice",
   "stem": "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
   "passage": "Every choice we make, however small, draws on the same limited pool of mental energy. Psychologists call the gradual exhaustion of this resource \"decision fatigue,\" and its effects are surprisingly wide-reaching. Judges, for instance, grant parole far more often early in the day than just before lunch, when their capacity for careful deliberation has been worn thin. The same mechanism explains why shoppers who have spent an hour comparing products often abandon their standards at the checkout, grabbing whatever is nearest. What looks like a failure of character is frequently just a brain that has run low on fuel. This is why many successful people deliberately reduce the number of trivial decisions they face, so that their sharpest judgment is saved for ________________.",
   "options": [
    "① the many small choices of daily life",
    "② whatever decision happens to come first",
    "③ the few decisions that truly matter",
    "④ the moments when they feel most tired",
    "⑤ tasks that others have already completed"
   ],
   "answer": "③",
   "typeId": "T-06",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "\"가장 중요한 소수 결정\"에 판단력 아껴둠(본문 what truly matters)"
  },
  {
   "id": "260714#10",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 10,
   "qtype": "choice",
   "stem": "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
   "passage": "Imagine a pasture shared by many herders, where anyone may graze as many animals as they wish. Each herder gains the full benefit of adding one more animal, while the cost of overgrazing is spread across everyone. Acting rationally in his own interest, each herder keeps adding animals, and the pasture is eventually destroyed. This grim logic, known as the tragedy of the commons, appears wherever a shared resource is open to all. It explains overfished oceans, polluted air, and crowded roads. The pattern reveals that individual rationality and collective well-being ________________.",
   "options": [
    "① always point in the same direction",
    "② can sharply conflict with each other",
    "③ depend entirely on government control",
    "④ matter only to professional economists",
    "⑤ steadily improve as more people join"
   ],
   "answer": "②",
   "typeId": "T-06",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "개인 합리성 ↔ 집단 후생이 충돌(공유지의 비극). ① 정반대(E1)"
  },
  {
   "id": "260714#11",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 11,
   "qtype": "choice",
   "stem": "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
   "passage": "During World War II, analysts examined planes returning from battle and noted where they were most often riddled with bullet holes: the wings and tail. The obvious response was to add armor to those areas. A statistician named Abraham Wald, however, reached the opposite conclusion. The planes he was studying were the ones that had survived; the bullet holes showed where a plane could be hit and still return home. The truly dangerous spots were the places with no holes at all, because planes struck there never made it back to be counted. Wald's insight was that the most important evidence was ________________.",
   "options": [
    "① found in the planes that never returned",
    "② visible in the most heavily damaged wings",
    "③ simply the number of bullet holes per plane",
    "④ far easier to gather than anyone expected",
    "⑤ irrelevant to the design of the armor"
   ],
   "answer": "①",
   "typeId": "T-06",
   "tier": "T4",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "생존자 편향—돌아오지 못한 비행기에 핵심 증거. 반직관 발상(T4)"
  },
  {
   "id": "260714#12",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 12,
   "qtype": "essay",
   "stem": "다음 글에서 전체 흐름과 **관계 없는** 문장은?",
   "passage": "Sleep does far more than rest the body; it actively strengthens what we learn. ① During deep sleep, the brain replays the day's experiences, transferring fragile new memories into more permanent storage. ② Students who sleep after studying consistently outperform those who stay awake, even when total study time is equal. ③ Regular physical exercise has been shown to lower the risk of heart disease in older adults. ④ Dreaming, which occurs mainly in the later stages of sleep, may help the brain connect new information to old knowledge. ⑤ For this reason, a full night's sleep before an exam is often more valuable than a few extra hours of review.\n---",
   "options": [],
   "answer": "③",
   "typeId": "T-09",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "운동-심장질환 문장은 수면·학습 주제와 무관"
  },
  {
   "id": "260714#13",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 13,
   "qtype": "choice",
   "stem": "주어진 글 다음에 이어질 글의 **순서**로 가장 적절한 것은?",
   "passage": "Paper money seems obviously convenient today, but its acceptance was once a remarkable leap of faith.\n- (A) This trust, however, took centuries to build, and early experiments often collapsed when governments printed too much.\n- (B) The idea first appeared in China, where merchants tired of hauling heavy strings of coins began leaving them with trusted agents in exchange for written receipts.\n- (C) Those receipts could then be traded directly, and people gradually accepted the paper itself as if it were the metal it represented.",
   "options": [
    "① (A)-(C)-(B)",
    "② (B)-(A)-(C)",
    "③ (B)-(C)-(A)",
    "④ (C)-(A)-(B)",
    "⑤ (C)-(B)-(A)"
   ],
   "answer": "③",
   "typeId": "T-07",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "(B)중국 기원→(C)영수증 유통→(A)신뢰는 수세기·붕괴"
  },
  {
   "id": "260714#14",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 14,
   "qtype": "choice",
   "stem": "주어진 글 다음에 이어질 글의 **순서**로 가장 적절한 것은?",
   "passage": "Fireflies flashing on a summer night are the most familiar example, but bioluminescence is far more common in the ocean.\n- (A) There, in the darkness of the deep sea, the ability has evolved independently many times.\n- (B) Each species uses its glow for a specific purpose, from luring prey to confusing predators.\n- (C) A few even use light to communicate, flashing signals that only members of their own kind can read.",
   "options": [
    "① (A)-(B)-(C)",
    "② (A)-(C)-(B)",
    "③ (B)-(A)-(C)",
    "④ (C)-(A)-(B)",
    "⑤ (C)-(B)-(A)"
   ],
   "answer": "①",
   "typeId": "T-07",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "(A)심해서 진화→(B)각 종의 용도→(C)일부는 소통"
  },
  {
   "id": "260714#15",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 15,
   "qtype": "essay",
   "stem": "글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?",
   "passage": "> Yet this seemingly empty symbol turned out to be one of the most powerful ideas in all of mathematics.\nFor most of history, people counted without any symbol for nothing. ( ① ) The ancient Romans, for example, had no zero, which made their numerals clumsy for calculation. ( ② ) The concept was fully developed in India, where scholars first treated zero as a number in its own right. ( ③ ) At first, many thinkers resisted the notion, unable to see how nothing could be something. ( ④ ) From there it spread to the Arab world and eventually to Europe. ( ⑤ ) Without it, modern arithmetic, algebra, and computing would be impossible.\n---",
   "options": [],
   "answer": "④",
   "typeId": "T-08",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "저항(③) 뒤 \"Yet 강력한 아이디어\" 대조 → ④ 자리"
  },
  {
   "id": "260714#16",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 16,
   "qtype": "essay",
   "stem": "글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?",
   "passage": "> When the water grows too warm, however, the coral expels these algae and turns a ghostly white.\nCoral reefs owe their brilliant colors to tiny algae that live inside them. ( ① ) These algae produce food through photosynthesis and share it with their coral hosts. ( ② ) In return, the coral provides the algae with shelter and nutrients, a partnership that has lasted for millions of years. ( ③ ) Stripped of its colorful partners, the coral is left starving and vulnerable. ( ④ ) If cooler conditions return quickly, the algae may come back and the reef can recover. ( ⑤ ) But if the heat persists, the coral dies, and the entire reef begins to collapse.\n---",
   "options": [],
   "answer": "③",
   "typeId": "T-08",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "삽입문(백화)이 ③ \"colorful partners를 잃고 굶주림\" 앞에 옴"
  },
  {
   "id": "260714#17",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 17,
   "qtype": "choice",
   "stem": "다음 글의 내용을 아래와 같이 요약하고자 한다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?",
   "passage": "Empathy and compassion are often treated as the same thing, yet researchers increasingly argue that they pull us in different directions. Empathy makes us feel another person's pain as if it were our own, which sounds admirable but can quietly exhaust us. Nurses and aid workers who absorb every patient's suffering frequently burn out and withdraw. Compassion, by contrast, does not require us to share the pain; it moves us to act to relieve it while keeping a steadying distance. In one study, volunteers trained in compassion reported more warmth and less distress than those trained only to empathize.\n> Although empathy makes us __(A)__ another's pain, it can lead to exhaustion; compassion instead drives us to __(B)__ while keeping emotional distance.\n(A)　　　(B)",
   "options": [
    "① share ...... help",
    "② ignore ...... help",
    "③ share ...... avoid",
    "④ cause ...... observe",
    "⑤ feel ...... criticize"
   ],
   "answer": "①",
   "typeId": "T-10",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "(A) share (B) help"
  },
  {
   "id": "260714#18",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 18,
   "qtype": "choice",
   "stem": "다음 글 [A], [B]를 읽고, 내용과 가장 **일치하는** 것은?",
   "passage": "[A] For centuries, solitude was seen as a path to wisdom. Philosophers and religious thinkers withdrew from society precisely because being alone allowed them to reflect deeply, free from the noise of others' opinions. In this tradition, the ability to be comfortable alone was a mark of maturity.\n[B] Modern psychology, however, warns that too much solitude can be harmful. Humans are social by nature, and prolonged isolation is linked to anxiety, depression, and even physical decline. From this view, regular connection with others is not a luxury but a basic need.",
   "options": [
    "① [A] regards solitude as a sign of immaturity.",
    "② [B] claims that humans thrive best in complete isolation.",
    "③ [A] and [B] both regard solitude as entirely harmful.",
    "④ [A] values solitude for reflection, while [B] warns of its dangers.",
    "⑤ [B] argues that connection with others is an unnecessary luxury."
   ],
   "answer": "④",
   "typeId": "T-12",
   "tier": "T4",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "[A]성찰 가치 / [B]위험 경고. ①②③⑤ 왜곡"
  },
  {
   "id": "260714#19",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 19,
   "qtype": "choice",
   "stem": "다음 글의 내용과 **일치하는** 것은?",
   "passage": "Before Johannes Gutenberg introduced movable type to Europe around 1450, books were copied by hand, a slow process that made them rare and expensive. Gutenberg's press did not invent printing itself, which had existed in East Asia for centuries, but it combined several innovations that made mass production practical in Europe. Within decades, the number of books in Europe multiplied enormously, and ideas that had once been confined to a few monasteries began to circulate widely. Historians often credit this flood of printed material with fueling the Reformation and the scientific revolution.",
   "options": [
    "① Gutenberg was the first person in the world to invent printing.",
    "② Before Gutenberg, European books were produced quickly and cheaply.",
    "③ Gutenberg's press had little effect on the spread of ideas.",
    "④ Printing had existed in East Asia before Gutenberg's press.",
    "⑤ The number of books in Europe fell after the press appeared."
   ],
   "answer": "④",
   "typeId": "T-02",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "인쇄술은 동아시아에 먼저 존재. ①②③⑤ 본문과 반대·왜곡"
  },
  {
   "id": "260714#20",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 20,
   "qtype": "choice",
   "stem": "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
   "passage": "Modern life is filling the world with noise, and researchers warn that we are losing something valuable: natural quiet. Constant background sound, from traffic to ventilation systems, keeps our nervous system in a low state of alert, subtly raising stress even when we stop noticing it. True silence, by contrast, gives the brain a chance to reset. In one experiment, two minutes of silence lowered blood pressure more than relaxing music did. This suggests that quiet is not merely the absence of sound but ________________.",
   "options": [
    "① a sign that something has gone wrong",
    "② an active ingredient of good health",
    "③ nearly impossible to find in a modern city",
    "④ far less important than pleasant music",
    "⑤ a distraction from truly meaningful work"
   ],
   "answer": "②",
   "typeId": "T-06",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "\"소리의 부재가 아니라 건강의 능동적 요소\". ④ 실험과 모순(E1)"
  },
  {
   "id": "260714#21",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 21,
   "qtype": "essay",
   "stem": "[서답형·조건 영작] 윗글(1번)의 내용을 바탕으로, 다음 우리말을 <조건>에 맞게 영작하시오. [4점]",
   "passage": "> 우리말: **여러 정보의 흐름을 다루는(juggle) 사람들은 한 가지 일에 집중하는 사람들보다 더 나쁜 성과를 낸다.**\n> <조건> ① **관계대명사를 반드시 포함**할 것. ② 다음 표현을 활용할 것(어형 변화 가능): `juggle several streams of information / perform / worse / than / those / focus on a single task`",
   "options": [],
   "answer": "People **who** juggle several streams of information perform worse than those who focus on a single task.",
   "typeId": "W-01",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "관계대명사 who 필수. 비교급 than"
  },
  {
   "id": "260714#22",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 22,
   "qtype": "essay",
   "stem": "[서답형·조건 영작] 다음 우리말을 <조건>에 맞게 영작하시오. [4점]",
   "passage": "> 우리말: **결정 피로라고 불리는 이 현상은 판사들에게서도 관찰되어 왔다.**\n> <조건> ① **수동태를 반드시 포함**할 것(현재완료 수동 사용). ② 다음 표현을 활용할 것(어형 변화 가능): `this phenomenon / call / decision fatigue / observe / in judges`",
   "options": [],
   "answer": "This phenomenon, **which is called** decision fatigue, **has been observed** in judges.",
   "typeId": "W-01",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "현재완료 수동(has been observed) 필수"
  },
  {
   "id": "260714#23",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 23,
   "qtype": "essay",
   "stem": "[서답형·어휘] <보기>에서 알맞은 표현을 골라 문장을 완성하시오. 필요하면 어형을 바꿀 것. [각 1점, 총 5점]",
   "passage": "> <보기> `run low on / burn out / stand out / carry a toll / come back`\n> (a) After months of overwork, many nurses eventually ________ and leave the profession.\n> (b) By evening, the judge's willpower had ________ fuel, and his decisions grew careless.\n> (c) Every task switch ________ on our concentration, even if we do not notice it.\n> (d) If cooler water returns, the algae may ________ and the reef can recover.\n> (e) In a sea of ordinary applications, her essay was the one that truly ________.",
   "options": [],
   "answer": "(a) burn out (b) run low on (c) carries a toll (d) come back (e) stood out",
   "typeId": "W-02",
   "tier": "T2",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "어형 변화: carries(3인칭), stood(과거)"
  },
  {
   "id": "260714#24",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 24,
   "qtype": "essay",
   "stem": "[서답형·서술] 9번 지문에서, **성공한 사람들이 사소한 결정의 수를 일부러 줄이는 이유**를 본문에 근거하여 우리말로 서술하시오. [4점, 부분점수 있음]",
   "passage": "",
   "options": [],
   "answer": "결정을 내릴 때마다 한정된 정신적 에너지가 소모되어(결정 피로) 판단력이 흐려지므로, 사소한 결정을 줄여 **가장 중요한 일에 가장 예리한 판단력을 아껴두기 위해서**.",
   "typeId": "W-03",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "부분점수: '에너지 소모' + '중요한 일에 판단력 보존'"
  },
  {
   "id": "260714#25",
   "sourceKey": "260714",
   "setId": "260714",
   "scopeConfirmed": false,
   "subject": "english",
   "number": 25,
   "qtype": "essay",
   "stem": "[서답형·영작] 다음 대화를 읽고, 전문가가 했을 조언을 **완결된 한 문장의 영어**로 쓰시오. (1번 지문의 요지를 반영할 것) [4점]",
   "passage": "> A: I try to study, check my phone, and listen to messages all at the same time, but somehow I remember almost nothing.\n> Expert: ________________________________________\n---\n---",
   "options": [],
   "answer": "(예시) \"You should focus on one task at a time, because switching between tasks leaves an 'attention residue' that weakens your memory and concentration.\"",
   "typeId": "W-04",
   "tier": "T3",
   "df": [],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "1번 요지(집중) 반영 + 완결 문장"
  },
  {
   "id": "SET-260822-math2-40#1",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 1,
   "qtype": "essay",
   "stem": "두 점 A(1, 3), B(5, 1)에서 같은 거리에 있는 x축 위의 점을 P라 하자.",
   "passage": "이때 AP²의 값을 구하시오.\n[SM2-01 · T1 · DF1]\n---",
   "options": [],
   "answer": "**10**",
   "typeId": "SM2-01",
   "tier": "T1",
   "df": [
    "DF1"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "P(t, 0)으로 두면 AP² = (t−1)²+9, BP² = (t−5)²+1. 등거리 조건에서 **t²이 상쇄**되어 −2t+10 = −10t+26 → t = 2. P(2, 0)이므로 AP² = 1+9 = **10**. / 함정: 제곱을 풀지 않고 이차방정식으로 오인. \"x축 위\"인데 x좌표를 0으로 두는 **축 혼동**(SM2-03 대표 오답과 같은 축). AP = √10을 답으로 쓰면 오답 — 묻는 것은 AP²."
  },
  {
   "id": "SET-260822-math2-40#2",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 2,
   "qtype": "essay",
   "stem": "한 변의 길이가 6인 정삼각형 ABC가 있다. 변 BC 위를 움직이는 점을 P라 하자.",
   "passage": "이때 AP² + 2BP²의 최솟값을 구하시오.\n[SM2-02 · T2 · DF1·DF5]\n---",
   "options": [],
   "answer": "**33**",
   "typeId": "SM2-02",
   "tier": "T2",
   "df": [
    "DF1",
    "DF5"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "**그림이 없으므로 좌표축을 스스로 세운다.** B(0, 0), C(6, 0), A(3, 3√3)로 두면 P(t, 0) (0 ≤ t ≤ 6). AP² = (t−3)²+27, BP² = t². f(t) = 3t²−6t+36 = 3(t−1)²+33 → t = 1일 때 최소 **33** (t = 1은 정의역 안). / 함정: 좌표 도입을 못 해 코사인법칙으로 우회(AP² = 36+t²−6t로 같은 결과). 계수 2를 빠뜨려 f(t)=2t²−6t+36로 계산. **최솟값을 주는 t(=1) 자체를 답으로 씀**. 정의역 [0, 6] 확인 누락."
  },
  {
   "id": "SET-260822-math2-40#3",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 3,
   "qtype": "essay",
   "stem": "두 점 A(a−4, 9−a), B(a+8, −a)에 대하여 선분 AB를 2 : 1로 내분하는 점을 P라 하자.",
   "passage": "점 P가 **제1사분면 위에 있도록** 하는 정수 a의 개수를 구하시오.\n[SM2-03 · T3 · DF1·DF2·DF4]\n---",
   "options": [],
   "answer": "**6**",
   "typeId": "SM2-03",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF4"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "2 : 1 내분점 P = ((2(a+8)+(a−4))/3, (2(−a)+(9−a))/3) = (**a+4, 3−a**). 제1사분면 ⇒ a+4 > 0 **그리고** 3−a > 0 ⇒ −4 < a < 3. 정수 a = −3, −2, −1, 0, 1, 2 → **6개**. / 함정(**E5 경계**): **사분면은 축을 포함하지 않아 등호가 없다.** a = −4면 P(0, 7)로 y축 위, a = 3이면 P(7, 0)로 x축 위 — 둘 다 제1사분면이 아니다. ≤로 잡으면 8개(오답). 또 하나: 내분비를 1 : 2로 뒤집으면 P(a, 6−a) → 5개(오답)."
  },
  {
   "id": "SET-260822-math2-40#4",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 4,
   "qtype": "essay",
   "stem": "두 점 A(−2, 1), B(4, 4)에 대하여 **직선 AB 위**의 점 C가 3AC = 5AB를 만족시킨다.",
   "passage": "(단, AC, AB는 각각 선분 AC, AB의 길이이다.)\n점 C의 x좌표와 y좌표의 합의 최댓값을 M, 최솟값을 m이라 할 때, M − m의 값을 구하시오.\n[SM2-04 · T3 · DF1·DF8]\n---",
   "options": [],
   "answer": "**30**",
   "typeId": "SM2-04",
   "tier": "T3",
   "df": [
    "DF1",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "AB 방향 성분은 (6, 3), 3AC = 5AB ⇒ AC = (5/3)AB이므로 C = A ± (5/3)(6, 3) = (−2, 1) ± (10, 5). C₁(8, 6), C₂(−12, −4). x+y는 각각 14, −16이므로 M = 14, m = −16, M − m = **30**. / 함정(**DF8 분기**): \"**직선 AB 위**\"는 A를 기준으로 **양방향 2해**다 — 한쪽만 구하면 M 또는 m이 사라진다(\"연장선 위 + 부호 단서\"였다면 1해). 3AC = 5AB를 뒤집어 AC = (3/5)AB로 쓰는 비례 오류. 기준점을 B로 잘못 잡음(이 문항의 기준은 **A**)."
  },
  {
   "id": "SET-260822-math2-40#5",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 5,
   "qtype": "essay",
   "stem": "삼각형 ABC의 두 꼭짓점이 A(−3, 4), B(5, −2)이고, 변 BC의 중점이 M(6, 3)이다.",
   "passage": "삼각형 ABC의 무게중심 G의 좌표를 (p, q)라 할 때, 3p + 6q의 값을 구하시오.\n[SM2-06 · T2 · DF1·DF9]\n---",
   "options": [],
   "answer": "**29**",
   "typeId": "SM2-06",
   "tier": "T2",
   "df": [
    "DF1",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "중점 조건에서 C = 2M − B = (12−5, 6+2) = (7, 8). G = ((−3+5+7)/3, (4−2+8)/3) = (3, 10/3). 3p+6q = 9+20 = **29**. (별해: G는 중선 AM을 A에서 2 : 1로 내분하므로 C를 구하지 않아도 된다.) / 함정: **계수 3, 6이 분모 3을 상쇄**하도록 설계돼 있어 G를 소수로 반올림하면 정수가 안 나온다(스스로 검산 가능). C = 2M − B의 **역산 방향을 뒤집어** C = (M+B)/2로 계산. G를 구하지 않고 M을 무게중심으로 착각."
  },
  {
   "id": "SET-260822-math2-40#6",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 6,
   "qtype": "essay",
   "stem": "(서술형) 다음 물음에 답하시오. **풀이 과정을 모두 쓰고, 결론을 문장으로 명확히 밝히시오.**",
   "passage": "(1) 좌표평면 위의 사각형 ABCD의 네 꼭짓점을 A(x₁, y₁), B(x₂, y₂), C(x₃, y₃), D(x₄, y₄)라 하고, 네 변 AB, BC, CD, DA의 중점을 각각 P, Q, R, S라 하자. 사각형 ABCD의 모양에 관계없이 **선분 PR의 중점과 선분 QS의 중점이 일치함**을 좌표를 이용하여 보이시오.\n(2) A(−3, 2), B(5, −4), C(7, 6)이고 사각형 ABCD가 평행사변형일 때(단, 네 꼭짓점은 A, B, C, D 순서로 놓인다), 점 D의 좌표를 구하고, (1)에서 일치함을 보인 그 중점의 좌표를 구하시오.\n[SM2-05 · T2 · DF1·DF2]\n---",
   "options": [],
   "answer": "**(1)** PR의 중점 = ((x₁+x₂+x₃+x₄)/4, (y₁+y₂+y₃+y₄)/4) = QS의 중점 (아래 해설) / **(2)** D(−1, 12), 중점 (2, 4)",
   "typeId": "SM2-05",
   "tier": "T2",
   "df": [
    "DF1",
    "DF2"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "**(1)** P((x₁+x₂)/2, (y₁+y₂)/2), R((x₃+x₄)/2, (y₃+y₄)/2)이므로 PR의 중점의 x좌표는 ((x₁+x₂)/2 + (x₃+x₄)/2)/2 = (x₁+x₂+x₃+x₄)/4. 마찬가지로 Q((x₂+x₃)/2, …), S((x₄+x₁)/2, …)에서 QS의 중점의 x좌표도 (x₂+x₃+x₄+x₁)/4. y좌표도 같은 방법으로 (y₁+y₂+y₃+y₄)/4로 일치한다. **따라서 사각형 ABCD의 모양에 관계없이 선분 PR의 중점과 선분 QS의 중점은 일치한다.** **(2)** 평행사변형 ABCD ⇔ 대각선 **AC와 BD**의 중점이 일치. AC의 중점 = (2, 4)이므로 (5+a)/2 = 2, (−4+b)/2 = 4 → **D(−1, 12)**. 그때 (1)의 중점은 ((−3+5+7−1)/4, (2−4+6+12)/4) = **(2, 4)**. / 함정: **좌표를 A(0,0), B(a,0) 같은 특수값으로 잡아 일반성을 잃음**(감점). 대각선을 AB·CD로 잘못 짝지음(최다 오답 — ABCD에서 대각선은 **AC·BD**). 결론 문장을 쓰지 않음."
  },
  {
   "id": "SET-260822-math2-40#7",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 7,
   "qtype": "essay",
   "stem": "두 점 A(1, −2), B(5, 4)를 지나는 직선에 수직이고, 점 C(4, 6)을 지나는 직선을 l이라 하자.",
   "passage": "직선 l의 x절편을 구하시오.\n[SM2-08 · T1 · DF1]\n---",
   "options": [],
   "answer": "**13**",
   "typeId": "SM2-08",
   "tier": "T1",
   "df": [
    "DF1"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "직선 AB의 기울기는 (4−(−2))/(5−1) = 3/2이므로 l의 기울기는 **−2/3**. C(4, 6)을 지나므로 y − 6 = −(2/3)(x − 4) ⇒ **2x + 3y − 26 = 0**. y = 0을 대입하면 x = **13**. / 함정: 수직 조건에서 기울기의 **역수만 취하고 부호를 빼먹음**(2/3로 계산 → x절편 −5). x절편과 y절편을 바꿔 답함(y절편은 26/3)."
  },
  {
   "id": "SET-260822-math2-40#8",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 8,
   "qtype": "essay",
   "stem": "두 직선 3x − 4y + 5 = 0, 3x − 4y − 15 = 0에 **동시에 접하고**, 중심이 직선 y = x 위에 있는 원이 있다.",
   "passage": "이 원의 중심의 좌표를 (a, b), 반지름의 길이를 r이라 할 때, a + b + r의 값을 구하시오.\n[SM2-11 · T2 · DF1·DF4]\n---",
   "options": [],
   "answer": "**−8**",
   "typeId": "SM2-11",
   "tier": "T2",
   "df": [
    "DF1",
    "DF4"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "두 직선은 평행하므로 사이의 거리는 \\"
  },
  {
   "id": "SET-260822-math2-40#9",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 9,
   "qtype": "essay",
   "stem": "두 점 A(a, 3), B(5, b)에 대하여 선분 AB의 수직이등분선의 방정식이 3x − 2y + 1 = 0이다.",
   "passage": "이때 ab의 값을 구하시오.\n[SM2-09 · T2 · DF1·DF9]\n---",
   "options": [],
   "answer": "**35**",
   "typeId": "SM2-09",
   "tier": "T2",
   "df": [
    "DF1",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "수직이등분선의 기울기가 3/2이므로 **① 직선 AB의 기울기 = −2/3**: (b − 3)/(5 − a) = −2/3 ⇒ 3b = 2a − 1. **② 중점 ((a+5)/2, (b+3)/2)가 수직이등분선 위**: 3(a+5) − 2(b+3) + 2 = 0 ⇒ 3a − 2b + 11 = 0. 연립하면 5a = −35 ⇒ **a = −7, b = −5**. ab = **35**. (검산: A(−7,3), B(5,−5)의 중점 (−1,−1)은 3x−2y+1=0 위, 기울기 −8/12 = −2/3.) / 함정: **두 조건 중 하나만 써서 미결정**(이 유형의 최대 오답원) — 수직 조건만 쓰면 a, b가 확정되지 않는다. 수직 기울기를 −3/2로 잘못 씀. ab 대신 a+b(=−12)를 답함. **DF9 역산** — 결과(수직이등분선)에서 원인(양 끝점)을 되짚는 구조."
  },
  {
   "id": "SET-260822-math2-40#10",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 10,
   "qtype": "essay",
   "stem": "두 직선 3x − 2y + 3 = 0, x + 4y − 13 = 0의 교점을 지나고, 점 A(5, 1)로부터의 거리가 4인 직선을 모두 구하시오.",
   "passage": "또, 이렇게 구한 직선들의 **x절편의 합**을 구하시오.\n[SM2-10 · T3 · DF1·DF2·DF8]\n---",
   "options": [],
   "answer": "직선: **x = 1**, **3x − 4y + 9 = 0** / x절편의 합 **−2**",
   "typeId": "SM2-10",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "두 직선을 연립하면 교점 **P(1, 3)**. \\"
  },
  {
   "id": "SET-260822-math2-40#11",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 11,
   "qtype": "essay",
   "stem": "삼각형 ABC의 세 꼭짓점이 A(2, 6), B(−4, 0), C(8, 0)이다. 꼭짓점 A를 지나는 직선 l이 변 BC와 만나 삼각형 ABC의 넓이를 **2 : 1로 나눈다.** (단, 꼭짓점 B를 포함하는 쪽의 넓이가 더 크다.)",
   "passage": "직선 l의 y절편을 구하시오.\n[SM2-13 · T2 · DF1·DF4]\n---",
   "options": [],
   "answer": "**12**",
   "typeId": "SM2-13",
   "tier": "T2",
   "df": [
    "DF1",
    "DF4"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "밑변 BC가 공통이므로 **넓이비 = 밑변비**. B 쪽이 2이므로 D는 BC를 **2 : 1로 내분**: D = (−4 + (2/3)·12, 0) = **(4, 0)**. 직선 l은 A(2, 6), D(4, 0)을 지나므로 기울기 −3, y = −3(x − 4) ⇒ y절편 **12**. / 함정(**방향 뒤집기**): \"B를 포함하는 쪽이 크다\"를 놓치면 1 : 2로 잡아 D = (0, 0) → l이 y = 3x가 되어 y절편 **0**(오답). 넓이(=36)를 실제로 계산하려는 우회는 불필요. 구하는 것이 y절편인데 x절편(=4)을 답함."
  },
  {
   "id": "SET-260822-math2-40#12",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 12,
   "qtype": "essay",
   "stem": "두 직선 3x − 4y + 5 = 0, 4x + 3y + 2 = 0에서 **같은 거리에 있는 x축 위의 점을 모두** 구할 때, 그 점들의 **x좌표의 곱**을 구하시오.",
   "passage": "[SM2-12 · T3 · DF1·DF8]\n---",
   "options": [],
   "answer": "**−3**",
   "typeId": "SM2-12",
   "tier": "T3",
   "df": [
    "DF1",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "두 직선의 법선 크기가 모두 5이므로 \\"
  },
  {
   "id": "SET-260822-math2-40#13",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 13,
   "qtype": "essay",
   "stem": "실수 k에 대하여 직선 kx − y − 3k + 2 = 0이 두 점 A(1, −4), B(0, 8)을 이은 **선분 AB와 만나도록** 하는 정수 k의 값의 **합**을 구하시오.",
   "passage": "[SM2-14 · T3 · DF1·DF2·DF4]\n---",
   "options": [],
   "answer": "**3**",
   "typeId": "SM2-14",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF4"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "k(x − 3) − y + 2 = 0으로 정리하면 k에 대한 항등식 조건에서 **정점 (3, 2)**를 지나고 **기울기가 k**인 직선이다(y의 계수가 −1이므로 수직선은 나오지 않는다). 정점에서 A(1, −4)를 보는 기울기는 (−4−2)/(1−3) = **3**, B(0, 8)을 보는 기울기는 (8−2)/(0−3) = **−2**. 선분 AB 위의 점을 (1−s, −4+12s)로 두면 기울기는 (6−12s)/(2+s)로 s에 대해 **단조감소**하며 3에서 −2까지 빠짐없이 훑는다(분모 2+s ≠ 0). 따라서 **−2 ≤ k ≤ 3**, 정수 k는 −2, −1, 0, 1, 2, 3의 6개이고 합은 **3**. / 함정(**E5 경계 — 이 학생의 1순위 취약축**): \"**선분** AB와 만난다\"는 **양 끝점 A, B를 포함**하므로 등호가 살아 있다. 등호를 빼면 k = −1, 0, 1, 2만 남아 합이 **2**(오답). 반대로 \"선분\"을 \"직선\"으로 읽으면 정점을 지나는 모든 직선이 만나 답이 존재하지 않는다. 또 하나: 정점을 구하지 않고 k를 하나씩 대입하는 무한 시도."
  },
  {
   "id": "SET-260822-math2-40#14",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 14,
   "qtype": "essay",
   "stem": "포물선 y = −x² + 6 위를 움직이는 점 P와 직선 y = 4x + 27 사이의 거리의 최솟값을 m이라 하고, 그때의 점 P의 x좌표를 t라 하자.",
   "passage": "m² + t의 값을 구하시오.\n[SM2-11 · T3 · DF1·DF5]\n---",
   "options": [],
   "answer": "**15**",
   "typeId": "SM2-11",
   "tier": "T3",
   "df": [
    "DF1",
    "DF5"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "직선을 4x − y + 27 = 0으로 정리(√(4²+1²) = √17). P(t, −t² + 6)에서의 거리는 \\"
  },
  {
   "id": "SET-260822-math2-40#15",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 15,
   "qtype": "essay",
   "stem": "(서술형) 좌표평면 위의 **마름모** ABCD에서 두 꼭짓점이 A(−1, 2), C(5, 6)이고, 마름모의 한 변의 길이가 √65이다. **풀이 과정을 모두 쓰시오.**",
   "passage": "(1) 대각선 BD를 포함하는 직선의 방정식을 구하시오.\n(2) 꼭짓점 B의 x좌표가 꼭짓점 D의 x좌표보다 클 때, 두 점 B, D의 좌표를 각각 구하시오.\n(3) 마름모 ABCD의 넓이를 구하시오.\n[SM2-09 · T4 · DF1·DF2·DF5·DF8]\n---",
   "options": [],
   "answer": "**(1)** 3x + 2y − 14 = 0 / **(2)** B(6, −2), D(−2, 10) / **(3)** 52",
   "typeId": "SM2-09",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "**(1)** 마름모의 두 대각선은 서로 **수직이등분**한다. AC의 중점 M(2, 4), 직선 AC의 기울기 (6−2)/(5+1) = 2/3이므로 BD의 기울기는 **−3/2**. y − 4 = −(3/2)(x − 2) ⇒ **3x + 2y − 14 = 0**. **(2)** MA = √(3² + 2²) = **√13**. 대각선이 수직이므로 직각삼각형 AMB에서 MB² = AB² − MA² = 65 − 13 = 52, **MB = 2√13**. BD의 방향은 기울기 −3/2, 즉 단위방향 (2, −3)/√13이므로 B = (2, 4) ± 2√13 · (2, −3)/√13 = (2, 4) ± (4, −6) ⇒ **(6, −2) 또는 (−2, 10)**. B의 x좌표가 더 크므로 **B(6, −2), D(−2, 10)**. **(3)** AC = 2√13, BD = 2·MB = 4√13이므로 넓이 = ½ · 2√13 · 4√13 = **52**. / 함정: **두 조건 중 수직 조건만 쓰고 \"중점을 지난다\"를 빠뜨림**(BD가 미결정). MB를 한 변 √65에서 곧바로 빼려 함 — **직각삼각형 AMB에서의 피타고라스**가 핵심 발상(DF5). 방향 성분에 √13을 곱하는 배율을 틀려 B가 격자점에서 벗어남. **두 해 중 선별 조건(B의 x좌표 > D의 x좌표)을 무시**(DF8). 넓이를 (한 변)² = 65로 오인 — 마름모는 정사각형이 아니다. 넓이 공식 ½d₁d₂에서 ½을 빠뜨려 104."
  },
  {
   "id": "SET-260822-math2-40#16",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 16,
   "qtype": "essay",
   "stem": "(서술형) 두 점 A(−3, −1), B(5, 7)과 점 P(1, 6)이 있다. 점 P를 지나면서 두 점 A, B로부터 **같은 거리에 있는** 직선을 생각하자. **풀이 과정을 모두 쓰시오.**",
   "passage": "(1) 조건을 만족시키는 직선의 방정식을 **모두** 구하고, 구한 것이 **전부임을 설명하시오.**\n(2) (1)에서 구한 직선들과 x축으로 둘러싸인 도형의 넓이를 구하시오.\n[SM2-13 · T4 · DF1·DF2·DF5·DF8 (+SM2-11)]\n---",
   "options": [],
   "answer": "**(1)** x = 1, x − y + 5 = 0 / **(2)** 18",
   "typeId": "SM2-13",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [
    "SM2-11"
   ],
   "tagExtra": [],
   "explanation": "**(1)** 점 P를 지나고 A, B에서 같은 거리인 직선은 **(ㄱ) 선분 AB와 평행한 직선** 또는 **(ㄴ) 선분 AB의 중점을 지나는 직선** 두 가지뿐이다(그 외에는 A, B가 직선의 서로 다른 쪽에 있으면서 거리가 달라진다). 직선 AB의 기울기는 (7+1)/(5+3) = **1**이므로 (ㄱ)은 y − 6 = x − 1 ⇒ **x − y + 5 = 0** (A, B에서의 거리 모두 3/√2). AB의 중점은 **M(1, 3)** 인데 **P(1, 6)과 x좌표가 같으므로** (ㄴ)은 **기울기가 존재하지 않는 x = 1** (A, B에서의 거리 모두 4). **(2)** x = 1과 x축의 교점 (1, 0), x − y + 5 = 0과 x축의 교점 (−5, 0), 두 직선의 교점 P(1, 6)이 꼭짓점이므로 밑변 6, 높이 6 ⇒ 넓이 = ½ · 6 · 6 = **18**. / 함정(**수직선 누락 — 부교재 #2-17 골격 재현**): y − 6 = m(x − 1)로 두고 \\"
  },
  {
   "id": "SET-260822-math2-40#17",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 17,
   "qtype": "essay",
   "stem": "중심이 직선 y = x − 1 위에 있고 두 점 A(1, 4), B(5, 2)를 지나는 원이 있다.",
   "passage": "이 원의 중심을 C(a, b), 반지름을 r라 할 때, a + b + r² 의 값을 구하시오.\n[SM2-15 · T1 · DF1]\n---",
   "options": [],
   "answer": "**13**",
   "typeId": "SM2-15",
   "tier": "T1",
   "df": [
    "DF1"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "중심을 C(a, a−1)로 **1미지수화**. CA² = 2a²−12a+26, CB² = 2a²−16a+34 → a=2. C(2,1), r²=10. a+b+r² = 2+1+10 = 13. **함정**: 중심을 (a,b) 두 미지수로 두면 계산량이 두 배가 된다."
  },
  {
   "id": "SET-260822-math2-40#18",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 18,
   "qtype": "essay",
   "stem": "원 C는 다음 두 조건을 모두 만족시킨다.",
   "passage": "> (가) 원 C는 x축에 접한다.\n> (나) 원 C의 중심은 직선 y = 2x − 4 위에 있고, 원 C는 점 A(1, 2)를 지난다.\n조건을 만족시키는 원은 두 개이다. 두 원의 반지름을 각각 r₁, r₂ 라 할 때 r₁r₂ 의 값을 구하시오.\n[SM2-16 · T2 · DF1·DF8]\n---",
   "options": [],
   "answer": "**20**",
   "typeId": "SM2-16",
   "tier": "T2",
   "df": [
    "DF1",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "중심 (a, 2a−4), x축 접 ⇒ r² = (2a−4)². 점 A 대입 → (1−a)²+(6−2a)² = (2a−4)² → a²−10a+21=0 → a=3, 7. 중심 (3,2) r=2 / (7,10) r=10. r₁r₂ = **20**. **함정**: a에 대한 이차방정식의 **두 근이 모두 유효**한데 한쪽만 답하고 끝냄(DF8). 접함을 대입 후 판별식으로 처리하면 4차식이 된다 — r = \\"
  },
  {
   "id": "SET-260822-math2-40#19",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 19,
   "qtype": "essay",
   "stem": "좌표평면에서 x축과 y축에 동시에 접하고, 직선 3x + 4y − 12 = 0 에도 접하는 원을 생각하자.",
   "passage": "이러한 원의 반지름을 모두 구하여, 그 값들의 합을 구하시오.\n[SM2-16 · T3 · DF1·DF2·DF8]\n---",
   "options": [],
   "answer": "**12**",
   "typeId": "SM2-16",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "양축 접 ⇒ 중심 (±t, ±t), r = t (t>0). 네 부호 계열을 모두 검사: (t,t) → \\"
  },
  {
   "id": "SET-260822-math2-40#20",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 20,
   "qtype": "essay",
   "stem": "두 점 A(−2, 0), B(4, 0)에 대하여 PA : PB = 2 : 1 을 만족시키는 점 P가 그리는 도형을 C라 하자.",
   "passage": "점 P가 도형 C 위를 움직일 때, 삼각형 PAB의 넓이의 최댓값을 구하시오.\n[SM2-17 · T2 · DF1·DF7]\n---",
   "options": [],
   "answer": "**12**",
   "typeId": "SM2-17",
   "tier": "T2",
   "df": [
    "DF1",
    "DF7"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "PA²=4PB² → (x+2)²+y² = 4{(x−4)²+y²} → x²+y²−12x+20=0 → (x−6)²+y²=16. 중심 (6,0), r=4. 밑변 AB=6은 x축 위로 **고정**이므로 높이의 최대 = r = 4. S = ½·6·4 = **12**. **함정**: 자취가 원임을 못 보고 대수 전개로 헤맴 / 밑변 고정 시 높이 최대 = 반지름임을 놓침."
  },
  {
   "id": "SET-260822-math2-40#21",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 21,
   "qtype": "essay",
   "stem": "방정식 x² + y² − 4x + 2y + k = 0 이 나타내는 도형이 **원**이고, 이 원이 직선 x + 2y + 5 = 0 과 **만나지 않도록** 하는 정수 k의 개수를 구하시오.",
   "passage": "[SM2-18 · T3 · DF1·DF2·DF4 · E5]\n---",
   "options": [],
   "answer": "**4**",
   "typeId": "SM2-18",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF4"
   ],
   "traps": [
    "E5"
   ],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "(x−2)²+(y+1)² = 5−k 이므로 **원이 될 조건 5−k>0 ⇒ k<5**. 중심 (2,−1)에서 직선까지 d = \\"
  },
  {
   "id": "SET-260822-math2-40#22",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 22,
   "qtype": "essay",
   "stem": "두 원",
   "passage": "> C₁ : x² + y² = 25\n> C₂ : x² + y² − 6x + 8y + 5 = 0\n이 서로 다른 두 점 A, B에서 만난다. 점 D(0, 5)에 대하여 삼각형 ABD의 넓이를 구하시오.\n[SM2-23 · T3 · DF1·DF2·DF7]\n---",
   "options": [],
   "answer": "**28**",
   "typeId": "SM2-23",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF7"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "공통현: C₁ − C₂ ⇒ 6x−8y−30=0 → **3x−4y−15=0**. 원점에서 이 직선까지 거리 3 ⇒ AB = 2√(25−9) = 8. 점 D(0,5)에서 직선까지 거리 = \\"
  },
  {
   "id": "SET-260822-math2-40#23",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 23,
   "qtype": "essay",
   "stem": "원 (x − 2)² + (y + 1)² = 5 에 접하고 기울기가 −2인 직선은 두 개이다.",
   "passage": "두 직선의 y절편을 각각 p, q라 할 때 pq의 값을 구하시오.\n[SM2-20 · T2 · DF1·DF8]\n---",
   "options": [],
   "answer": "**−16**",
   "typeId": "SM2-20",
   "tier": "T2",
   "df": [
    "DF1",
    "DF8"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "중심 (2,−1), r=√5. **이동한 원**이므로 y+1 = −2(x−2) ± √5·√((−2)²+1) = −2(x−2) ± 5. 두 접선 y = −2x+8, y = −2x−2. pq = 8·(−2) = **−16**. **함정**: 원점 중심 공식 y = mx ± r√(m²+1)을 이동한 원에 그대로 적용(대표 오답, y절편 ±5가 나옴) / 두 접선 사이 거리는 10/√5 = 2√5 = 2r 로 검산 가능."
  },
  {
   "id": "SET-260822-math2-40#24",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 24,
   "qtype": "essay",
   "stem": "원 x² + y² = 10 위의 점 P(a, b) (a > 0, b > 0)에서의 접선이 직선 x + 3y + 1 = 0 과 평행하다.",
   "passage": "ab의 값을 구하시오.\n[SM2-21 · T1 · DF1]\n---",
   "options": [],
   "answer": "**3**",
   "typeId": "SM2-21",
   "tier": "T1",
   "df": [
    "DF1"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "P(a,b)에서의 접선은 **ax + by = 10**, 기울기 −a/b. 주어진 직선의 기울기 −1/3과 같으므로 b = 3a. 원 위의 점이므로 a²+b² = 10 → 10a² = 10 → a=1(a>0), b=3. ab = **3**. **함정**: 접선을 다시 유도하려 함 / a²+b²=r² 조건을 연립에 넣지 않아 미결정 / b=0 예외 확인."
  },
  {
   "id": "SET-260822-math2-40#25",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 25,
   "qtype": "essay",
   "stem": "원 C : x² + y² = 9 의 외부에 있는 점 P(a, b)에서 원 C에 그은 두 접선의 접점을 각각 A, B라 하자. 두 점 A, B를 지나는 직선의 방정식이 2x − y = 3 이다.",
   "passage": "삼각형 PAB의 넓이를 S라 할 때, 5S의 값을 구하시오.\n[SM2-22 · T4 · DF1·DF2·DF5·DF9]\n---",
   "options": [],
   "answer": "**72**",
   "typeId": "SM2-22",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "접점을 지나는 직선(접점현)은 **ax + by = 9**. 이것이 2x−y=3, 즉 6x−3y=9 와 같으므로 P(6, −3). d = OP = √45 = 3√5 (원 밖 확인: 45>9). 중심에서 AB까지 거리 = r²/d = 9/(3√5) = 3/√5 ⇒ AB = 2√(9−9/5) = 12/√5. 높이 = d − r²/d = 12/√5. S = ½·(12/√5)² = 72/5 ⇒ 5S = **72**. **함정(DF9)**: 두 접점 좌표를 연립으로 직접 구하려다 계산 폭증 / 2x−y=3 의 우변을 9로 맞추는 **비례 조정을 빼먹고** a=2, b=−1 로 읽어 P(2,−1)로 오산(이 점은 원 밖이지만 접점현이 2x−y=9 가 되어 조건과 불일치) / 접선의 길이 PA = √(45−9) = 6 으로 검산 가능."
  },
  {
   "id": "SET-260822-math2-40#26",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 26,
   "qtype": "essay",
   "stem": "원 C : (x − 1)² + (y + 2)² = 16 과 직선 l : 3x − 4y + 24 = 0 이 있다.",
   "passage": "원 C 위의 점 P와 직선 l 사이의 거리가 자연수가 되도록 하는 점 P의 개수를 구하시오.\n[SM2-25 · T3 · DF1·DF2·DF4 · E5]\n---",
   "options": [],
   "answer": "**16**",
   "typeId": "SM2-25",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF4"
   ],
   "traps": [
    "E5"
   ],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "중심 (1,−2)에서 l까지 d = \\"
  },
  {
   "id": "SET-260822-math2-40#27",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 27,
   "qtype": "essay",
   "stem": "(서술형) 두 점 A(−1, 2), B(3, −2)와 원 C : (x − 4)² + (y − 5)² = 8 위를 움직이는 점 P가 있다.",
   "passage": "삼각형 PAB의 넓이가 최대일 때, 점 P의 좌표와 그때의 넓이를 구하시오. **풀이 과정을 함께 쓰시오.**\n> 채점 조건\n> (1) 직선 AB의 방정식과 선분 AB의 길이를 구할 것\n> (2) 원의 중심에서 직선 AB까지의 거리와 반지름을 비교하여 높이의 최댓값을 구할 것\n> (3) 점 P의 좌표와 넓이를 모두 밝힐 것\n[SM2-25 · T4 · DF1·DF2·DF5]\n---",
   "options": [],
   "answer": "**P(6, 7), 넓이 24**",
   "typeId": "SM2-25",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "① 직선 AB: 기울기 −1, **x+y−1=0**, AB = √(4²+(−4)²) = 4√2. ② 중심 (4,5)에서 AB까지 거리 d = \\"
  },
  {
   "id": "SET-260822-math2-40#28",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 28,
   "qtype": "essay",
   "stem": "두 원",
   "passage": "> C₁ : (x − 1)² + (y − 2)² = 4\n> C₂ : (x − 6)² + (y − 14)² = 49\n는 서로 외부에 있다. 두 원의 **공통외접선** 한 개가 C₁, C₂와 접하는 점을 각각 P, Q라 할 때, 선분 PQ의 길이를 구하시오.\n[SM2-24 · T2 · DF1·DF2]\n---",
   "options": [],
   "answer": "**12**",
   "typeId": "SM2-24",
   "tier": "T2",
   "df": [
    "DF1",
    "DF2"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "중심 (1,2), (6,14) ⇒ d = √(5²+12²) = 13. r₁+r₂ = 9 < 13 이므로 두 원은 서로 **외부**에 있다(공통접선 4개). 공통**외**접선의 접점 거리 = √(d² − (r₁−r₂)²) = √(169−25) = **12**. **함정(E9)**: 내접선 공식 √(d²−(r₁+r₂)²) = √(169−81) = √88 을 쓰는 **공식 쌍 혼동 — 이 유형의 1번 오답원** / 위치 관계를 먼저 판정하지 않음."
  },
  {
   "id": "SET-260822-math2-40#29",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 29,
   "qtype": "essay",
   "stem": "두 원",
   "passage": "> C₁ : x² + y² + 4x − 2y + 1 = 0\n> C₂ : x² + y² − 8x − 18y + 81 = 0\n이 있다. 두 원의 중심을 각각 O₁, O₂라 하자. 두 원에 동시에 접하는 직선 중 **선분 O₁O₂와 만나는** 직선을 l이라 하고, l이 C₁, C₂와 접하는 점을 각각 P, Q라 할 때 선분 PQ의 길이를 구하시오.\n[SM2-24 · T3 · DF1·DF2·DF4 · E9]\n---",
   "options": [],
   "answer": "**8**",
   "typeId": "SM2-24",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF4"
   ],
   "traps": [
    "E9"
   ],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "완전제곱: C₁ → (x+2)²+(y−1)² = 4 (중심 (−2,1), r₁=2), C₂ → (x−4)²+(y−9)² = 16 (중심 (4,9), r₂=4). d = √(6²+8²) = 10 > r₁+r₂ = 6 ⇒ 외부. **\"선분 O₁O₂와 만나는 접선\" = 공통내접선**이므로 PQ = √(d²−(r₁+r₂)²) = √(100−36) = **8**. **함정(E9)**: 외접선 공식으로 √(100−4) = 4√6 을 답함 / 일반형에서 r² = (A/2)²+(B/2)²−C 계산 실수(C₂의 상수항 81이 그대로 상쇄) / \"선분과 만난다\"는 단서를 무시하고 아무 접선으로 봄."
  },
  {
   "id": "SET-260822-math2-40#30",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 30,
   "qtype": "essay",
   "stem": "(서술형) 두 원",
   "passage": "> C₁ : (x + 4)² + (y + 1)² = 49\n> C₂ : (x − 4)² + (y − 14)² = r² (r > 0)\n는 서로 외부에 있다. 두 원의 중심을 각각 O₁, O₂라 하자. 두 원에 동시에 접하는 직선 중 **선분 O₁O₂와 만나는** 직선이 C₁, C₂와 접하는 점을 각각 A, B라 하면 AB = 8 이다.\n(1) r의 값을 구하시오.\n(2) 이때 두 원의 공통외접선의 두 접점 사이의 거리를 구하시오.\n**풀이 과정을 함께 쓰시오.**\n> 채점 조건\n> (1) 두 중심 사이의 거리 d를 구할 것\n> (2) 사용한 접점 사이 거리 공식이 **공통내접선**의 것임을 밝힐 것\n> (3) (2)에서는 **공통외접선** 공식으로 바꾸어 쓸 것\n[SM2-24 · T4 · DF1·DF2·DF5·DF9]\n---",
   "options": [],
   "answer": "**(1) r = 8  (2) 12√2**",
   "typeId": "SM2-24",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "① 중심 O₁(−4,−1), O₂(4,14) ⇒ d = √(8²+15²) = **17**. ② 선분 O₁O₂와 만나는 접선 = **공통내접선**이므로 AB = √(d²−(r₁+r₂)²) = √(289−(7+r)²) = 8 ⇒ (7+r)² = 225 ⇒ 7+r = 15 (r>0) ⇒ **r = 8**. 외부 조건 확인: r₁+r₂ = 15 < 17 ✓ (공통접선 4개, 내접선 존재). ③ 같은 두 원의 공통**외**접선 접점 거리 = √(d²−(r₂−r₁)²) = √(289−(8−7)²) = √288 = **12√2**. **함정(DF9+E9)**: 역산 단계에서 외접선 공식을 써 (r−7)²=225 ⇒ r=22 로 답함(그러면 d=17 < r₁+r₂=29 라 두 원이 외부에 있다는 조건과 **모순** — 이 모순 점검이 자기검산) / (2)에서 공식을 다시 내접선으로 씀 / 7+r = −15 를 버리는 근거(r>0) 누락."
  },
  {
   "id": "SET-260822-math2-40#31",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 31,
   "qtype": "essay",
   "stem": "평행이동 f는 점 (3, −1)을 점 (−1, 4)로 옮긴다. 평행이동 f에 의하여 삼각형 ABC가 삼각형 A′B′C′으로 옮겨지고, 삼각형 A′B′C′의 무게중심의 좌표는 (2, 5)이다.",
   "passage": "삼각형 ABC의 세 꼭짓점의 x좌표의 합을 m, y좌표의 합을 n이라 할 때, m + n 의 값을 구하시오.\n[SM2-26 · T2 · DF1·DF9]\n---",
   "options": [],
   "answer": "**18**",
   "typeId": "SM2-26",
   "tier": "T2",
   "df": [
    "DF1",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "(3,−1)→(−1,4)이므로 이동량은 (−4, 5). 무게중심도 같은 양만큼 옮겨지므로 ABC의 무게중심 = (2+4, 5−5) = (6, 0). 세 꼭짓점 좌표의 합 = 무게중심의 3배 ⇒ m=18, n=0, m+n=**18**. / **함정**: 이동 방향 역전(무게중심을 (−2,10)으로) → 답 −6. 세 꼭짓점을 개별로 이동하려는 우회."
  },
  {
   "id": "SET-260822-math2-40#32",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 32,
   "qtype": "essay",
   "stem": "포물선 y = x² − 6x + 11 을 평행이동하면 포물선 y = x² + 2x + 6 과 완전히 겹쳐진다.",
   "passage": "이 평행이동에 의하여 직선 2x − y + 1 = 0 이 직선 l로 옮겨질 때, 직선 l과 x축 및 y축으로 둘러싸인 삼각형의 넓이를 구하시오.\n[SM2-27 · T2 · DF1·DF9]\n---",
   "options": [],
   "answer": "**36**",
   "typeId": "SM2-27",
   "tier": "T2",
   "df": [
    "DF1",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "두 포물선의 꼭짓점 (3, 2) → (−1, 5)이므로 이동량 (−4, 3). 직선의 상은 x→x+4, y→y−3 대입: 2(x+4)−(y−3)+1=0 ⇒ y = 2x + 12. x절편 −6, y절편 12 ⇒ 넓이 = ½·6·12 = **36**. / **함정**: 대입 부호를 반대로(x→x−4) 하면 y=2x−4, 넓이 4. 계수 비교로 이동량을 추정하려다 상수항만 보고 오판."
  },
  {
   "id": "SET-260822-math2-40#33",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 33,
   "qtype": "essay",
   "stem": "점 P(a, b)를 직선 y = x에 대하여 대칭이동한 점을 Q라 하고, 점 Q를 y축에 대하여 대칭이동한 점을 R라 하자. 점 R는 제2사분면 위에 있고, 점 P는 직선 x + 2y = 12 위에 있다.",
   "passage": "a, b가 정수일 때, ab의 최솟값을 구하시오.\n[SM2-29 · T3 · DF1·DF2·DF8 · E5]\n---",
   "options": [],
   "answer": "**10**",
   "typeId": "SM2-29",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF8"
   ],
   "traps": [
    "E5"
   ],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "P(a,b) →(y=x)→ Q(b,a) →(y축)→ R(−b, a). R가 제2사분면 ⇒ −b<0, a>0 ⇒ **a>0, b>0**(등호 없음). a+2b=12인 양의 정수해는 (10,1),(8,2),(6,3),(4,4),(2,5). ab=**10**,16,18,16,10 ⇒ 최솟값 **10**(a=10,b=1 및 a=2,b=5에서). / **함정(E5)**: 사분면은 축을 포함하지 않으므로 b=6(a=0), b=0(a=12)은 제외 — 등호를 넣으면 ab=0이 최솟값으로 둔갑한다. 사분면 조건을 아예 무시하면 b가 커질수록 ab→−∞라 **최솟값이 존재하지 않는다** — 즉 이 문항은 대칭이동 조건이 답을 만드는 구조다. 대칭 순서를 뒤집어 R=(−a,b)로 두면 부등식이 반대로 나옴."
  },
  {
   "id": "SET-260822-math2-40#34",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 34,
   "qtype": "essay",
   "stem": "원 x² + y² + 2x − 6y + 2 = 0 을 x축의 방향으로 3만큼, y축의 방향으로 −2만큼 평행이동한 원을 C라 하자.",
   "passage": "원 C와 직선 y = x + k 가 만나도록 하는 정수 k의 개수를 구하시오.\n[SM2-28 · T3 · DF1·DF2 · E5]\n---",
   "options": [],
   "answer": "**9**",
   "typeId": "SM2-28",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2"
   ],
   "traps": [
    "E5"
   ],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "원은 (x+1)²+(y−3)²=8, 중심 (−1,3), r=2√2. 평행이동 후 중심 (2, 1), r=2√2. 직선 x−y+k=0 과 **만난다 ⇒ d ≤ r**: \\"
  },
  {
   "id": "SET-260822-math2-40#35",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 35,
   "qtype": "essay",
   "stem": "원 C: (x − 2)² + (y + 1)² = r² (r > 0) 을 x축의 방향으로 p만큼, y축의 방향으로 q만큼 평행이동한 원을 C′이라 하자. 원 C′은 x축과 y축에 모두 접하고, C′의 중심은 직선 y = 2x + 3 위에 있다.",
   "passage": "이때 조건을 만족시키는 모든 순서쌍 (p, q, r)에 대하여 p + q 의 값의 합을 구하시오.\n[SM2-28 · T4 · DF1·DF2·DF8·DF9 · E9]\n---",
   "options": [],
   "answer": "**−8**",
   "typeId": "SM2-28",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF8",
    "DF9"
   ],
   "traps": [
    "E9"
   ],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "C′의 중심은 (2+p, −1+q). 이를 (t, s)라 하면 양축에 접하므로 \\"
  },
  {
   "id": "SET-260822-math2-40#36",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 36,
   "qtype": "essay",
   "stem": "실수 k의 값에 관계없이 직선 l: (k + 2)x − (k − 1)y + 3k = 0 은 항상 일정한 점을 지난다. 직선 l을 원점에 대하여 대칭이동한 직선을 l′이라 하면, 직선 l′ 또한 k의 값에 관계없이 항상 일정한 점 A를 지난다.",
   "passage": "원 C: x² + y² − 6x − 4y + 4 = 0 의 넓이를 이등분하고 점 A를 지나는 직선의 방정식을 y = mx + n 이라 할 때, m + n 의 값을 구하시오.\n[SM2-30 · T3 · DF1·DF2·DF7]\n---",
   "options": [],
   "answer": "**−2**",
   "typeId": "SM2-30",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF7"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "원점 대칭: x→−x, y→−y ⇒ l′: (k+2)x−(k−1)y−3k=0. k에 대해 정리하면 k(x−y−3)+(2x+y)=0 ⇒ x−y−3=0, 2x+y=0 ⇒ **A(1, −2)**. 원은 (x−3)²+(y−2)²=9, 중심 (3,2). 넓이 이등분 직선은 **중심을 지나므로** 기울기 m=(2+2)/(3−1)=2, y=2x+n에 (1,−2) 대입 ⇒ n=−4. m+n=**−2**. / **함정**: 대칭이동을 하지 않고 원래 l의 정점 (−1, 2)를 쓰면 기울기 0, n=2 ⇒ m+n=2(대표 오답). 넓이 이등분을 \"현의 중점\"으로 오해."
  },
  {
   "id": "SET-260822-math2-40#37",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 37,
   "qtype": "essay",
   "stem": "(서술형) 좌표평면 위의 도형 F가 방정식 f(x, y) = 0 으로 나타내어진다. 도형 F를 직선 y = x에 대하여 대칭이동한 후, 그 도형을 다시 x축의 방향으로 −2만큼, y축의 방향으로 4만큼 평행이동한 도형을 G라 하자.",
   "passage": "(1) 도형 G를 나타내는 방정식을 f를 사용하여 나타내시오.\n(2) f(x, y) = (x − 1)² + (y + 3)² − 4 일 때, 도형 G의 중심의 좌표를 구하시오.\n(1), (2)의 풀이 과정을 모두 서술하시오.\n> 채점 조건\n> (1) y = x 대칭에서 **두 변수를 서로 바꾸는 것**임을 밝힐 것\n> (2) 도형을 옮기면 식에는 **반대 부호**가 들어감을 밝히고, 합성 순서(대칭 → 평행이동)를 지킬 것\n> (3) f(y − 4, x + 2) = 0 에 실제로 대입·전개하여 중심 (−5, 5)를 밝힐 것\n[SM2-31 · T3 · DF1·DF9]\n---",
   "options": [],
   "answer": "**(1)** f(y − 4, x + 2) = 0 / **(2)** (−5, 5)",
   "typeId": "SM2-31",
   "tier": "T3",
   "df": [
    "DF1",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "**(1)** F 위의 점 (a,b)(f(a,b)=0)가 y=x 대칭으로 (b,a), 이어 평행이동으로 (b−2, a+4)로 간다. 이를 (x,y)라 두면 b=x+2, a=y−4. f(a,b)=0에 대입하면 G: **f(y − 4, x + 2) = 0**. **(2)** 대입하면 (y−4−1)²+(x+2+3)²−4=0 ⇒ (x+5)²+(y−5)²=4 ⇒ 중심 **(−5, 5)**. (검산: 중심 (1,−3) →y=x대칭→ (−3,1) →평행이동→ (−5,5).) / **함정**: 합성 **순서를 뒤바꿔** 평행이동을 먼저 적용 / 도형을 옮기면 식에는 **반대 부호**가 들어간다는 점을 놓쳐 f(y+4, x−2)=0으로 씀 / y=x 대칭에서 두 변수를 바꾸지 않음."
  },
  {
   "id": "SET-260822-math2-40#38",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 38,
   "qtype": "essay",
   "stem": "(서술형) 원 C: x² + y² − 2x + 12y + 28 = 0 을 직선 l: y = 2x − 3 에 대하여 대칭이동한 원을 C′이라 하고, 원 C′을 다시 x축에 대하여 대칭이동한 원을 C″이라 하자.",
   "passage": "원 C″의 방정식을 구하는 과정을 서술하고, C″의 중심의 좌표를 (a, b), 반지름의 길이를 r이라 할 때 a + b + r 의 값을 구하시오.\n> 채점 조건\n> (1) **반지름은 대칭이동에서 불변**임을 밝히고 중심만 추적할 것\n> (2) **중점 조건**과 **수직 조건** 두 식을 모두 세울 것 (하나만 세우면 미결정)\n> (3) 마지막 **x축 대칭까지 합성**했음을 확인하고 C″의 방정식을 밝힐 것\n⚠️ 부교재 근거 — 교육과정 명시 범위 초과\n[SM2-32 · T3 · DF1·DF2·DF9]\n---",
   "options": [],
   "answer": "**(x + 3)² + (y − 4)² = 9, a+b+r = 4**",
   "typeId": "SM2-32",
   "tier": "T3",
   "df": [
    "DF1",
    "DF2",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "C: (x−1)²+(y+6)²=9, 중심 A(1,−6), r=3. **반지름은 대칭이동에서 불변**이므로 중심만 옮기면 된다. A′(p,q)라 하면 ① 중점 ((1+p)/2, (−6+q)/2)이 l 위: (−6+q)/2 = 2·(1+p)/2 − 3 = p − 2 ⇒ −6+q = 2p−4 ⇒ **q = 2p + 2**. ② AA′ ⊥ l: (q+6)/(p−1) = −½ ⇒ p + 2q = −11. 연립하면 p=−3, q=−4 ⇒ A′(−3,−4). (검산: 반사 공식 — l을 2x−y−3=0으로 두면 k = (2·1+6−3)/(2²+1²) = 1, A′ = (1−2·2·1, −6−2·(−1)·1) = (−3,−4) ✓) 이를 x축 대칭 ⇒ (−3, 4). C″: **(x+3)²+(y−4)²=9**, a+b+r = −3+4+3 = **4**. / **함정**: ②(수직 조건) 누락이 최대 오답원 — 중점 조건만 쓰면 미결정. 수직 기울기 −1/m의 부호 실수. **마지막 x축 대칭 합성을 잊음**(답 (x+3)²+(y+4)²=9). 반지름까지 대칭시키려는 시도. ⚠️ 부교재 근거 — 교육과정 명시 범위 초과."
  },
  {
   "id": "SET-260822-math2-40#39",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 39,
   "qtype": "essay",
   "stem": "좌표평면 위에 두 점 A(1, 2), D(4, 6)이 있고, x축 위에 두 점 B, C가 있다. 점 B의 x좌표는 점 C의 x좌표보다 작고 BC = 9 이다.",
   "passage": "이때 AB + BC + CD + DA 의 최솟값을 구하시오.\n[SM2-33 · T4 · DF1·DF2·DF5]\n---",
   "options": [],
   "answer": "**24**",
   "typeId": "SM2-33",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "**DA = √(3²+4²) = 5 와 BC = 9 는 이미 고정**이므로 최소화 대상은 AB + CD뿐이다. B(t, 0), C(t+9, 0)이므로 CD = dist((t+9,0),(4,6)) = dist((t,0), **D′(−5, 6)**) — D를 x축 방향으로 −9만큼 평행이동. 또 A(1,2)를 x축에 대하여 대칭시켜 **A′(1, −2)**. 그러면 AB+CD = A′B + BD′ ≥ A′D′ = √(6²+8²) = 10 (B가 선분 A′D′ 위, 즉 B(−½, 0)일 때 등호). 최솟값 = 10 + 9 + 5 = **24**. / **함정**: 고정된 DA·BC까지 최소화하려 함 / BC=9를 더하는 것을 잊어 15 / **평행이동(−9, 0)을 빼고 대칭만** 적용해 A′D = √73 / A와 D를 모두 대칭시킴."
  },
  {
   "id": "SET-260822-math2-40#40",
   "sourceKey": "260822",
   "setId": "SET-260822-math2-40",
   "scopeConfirmed": false,
   "subject": "math2",
   "number": 40,
   "qtype": "essay",
   "stem": "(서술형) 좌표평면 위에 점 A(1, 3)과 원 C: (x − 6)² + (y + 4)² = 9 가 있다. 점 P는 y축 위를 움직이고, 점 Q는 원 C 위를 움직인다.",
   "passage": "AP + PQ 의 최솟값을 m이라 할 때 m = a + b√2 (a, b는 유리수)이다. ab의 값과, m이 최소가 될 때의 점 P의 좌표를 구하고 풀이 과정을 서술하시오.\n> 채점 조건\n> (1) 점 A와 원의 중심 C가 **y축의 같은 쪽**에 있어 A의 y축 대칭점 A′를 쓴다는 근거를 밝힐 것\n> (2) **PQ ≥ PC − r** 로 치환하고, 이어 A′P + PC ≥ A′C 임을 밝힐 것\n> (3) 등호 성립 조건(**P가 선분 A′C 위**)을 밝혀 점 P의 좌표까지 구할 것\n[SM2-33 · T4 · DF1·DF2·DF5·DF9]\n---",
   "options": [],
   "answer": "**ab = −21, P(0, 2)**",
   "typeId": "SM2-33",
   "tier": "T4",
   "df": [
    "DF1",
    "DF2",
    "DF5",
    "DF9"
   ],
   "traps": [],
   "auxTypes": [],
   "tagExtra": [],
   "explanation": "점 A(1,3)과 원의 중심 C(6,−4)는 **모두 y축의 오른쪽**(같은 쪽)이므로 대칭이 필요하다. A를 y축에 대하여 대칭시키면 **A′(−1, 3)**, AP = A′P. 또 Q가 원 위의 자유점이므로 **PQ ≥ PC − r = PC − 3**. 따라서 AP + PQ ≥ A′P + PC − 3 ≥ **A′C − 3** = √((6+1)²+(−4−3)²) − 3 = 7√2 − 3. 즉 m = −3 + 7√2 ⇒ a=−3, b=7, **ab = −21**. 등호는 P가 선분 A′C 위에 있을 때: 직선 A′C는 y = −x + 2 이므로 y축과의 교점 **P(0, 2)**. (검산: AP=√2, PC=6√2 ⇒ √2 + 6√2 − 3 = 7√2 − 3.) / **함정**: **반지름 가감을 잊어** 7√2(a=0, ab=0) / 부호를 반대로 하여 7√2+3 / 대칭을 하지 않고 AC − r = √74 − 3 / 최솟값만 구하고 **그때의 점 P를 구하지 않음**."
  }
 ]
};
